In [2]:
print("hi")

hi


In [3]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4,5])
type(a1)

numpy.ndarray

In [5]:
ar1 = np.random.randn(3,2)
ar1

array([[-0.29797369, -0.16805557],
       [ 0.31692202, -0.85518398],
       [-0.90801451, -0.23073131]])

In [10]:
x = np.arange(1,10,2) 
x

array([1, 3, 5, 7, 9])

In [11]:
x.ndim

1

In [12]:
x.shape

(5,)

In [13]:
change = "please"

In [14]:
x[3]

7

In [15]:
x[2:]

array([5, 7, 9])

In [16]:
x[2:5]

array([5, 7, 9])

In [20]:
x = np.random.randnit(10, size=(2,6))
x

AttributeError: module 'numpy.random' has no attribute 'randnit'